In [1]:
import numpy as np


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [11]:
def sigmoid_derivate(x):
    return x*(1-x)

In [3]:
training_inputs=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_outputs=np.array([[0,1,1,0]]).T



In [4]:
np.random.seed(1)

In [5]:
synaptic_weights = 2*np.random.random((3,1))-1
print("Random starting synaptic weights:")
print(synaptic_weights)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [12]:
for iteration in range(20000):
    input_layer=training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error= training_outputs - outputs
    
    adjustments= error * sigmoid_derivate(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print("synaptic weights after training:")
print(synaptic_weights)
    
print("Outputs after training:")
print(outputs)

synaptic weights after training:
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Outputs after training:
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


In [ ]:
# x1=0, x2=0, x3=1 
# w1=-0.165, w2=0.44, w3=-0.99
# X=Sum(x1w1+x2w2+x3w3...)
# y=sigmod(X)
# Calculation with random weights

In [ ]:
# Training Process
# 1. Take the inputs from the training example, and put them through our formula to get the neuron's output
# 2. Calculate the error which is the difference between the output we got and the acutal output
# 3. Depending on severeness of the error and adjust the weights accordingly
# 4. Repeat this 20000 times


In [ ]:
# Error Weighted dy/dx
# Adjusts weights by =error.input.changes(output)